parameters:
    default_admin_email: admin@example.com
    default_domain: localhost
    default_scheme: http
    router.request_context.host: '%env(default:default_domain:SYMFONY_DEFAULT_ROUTE_HOST)%'
    router.request_context.scheme: '%env(default:default_scheme:SYMFONY_DEFAULT_ROUTE_SCHEME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $adminEmail: '%env(string:default:default_admin_email:ADMIN_EMAIL)%'
            string $akismetKey: '%env(AKISMET_API_KEY)%'
            string $akismetEndpoint: '%env(AKISMET_ENDPOINT)%'
            string $photoDir: "%kernel.project_dir%/public/uploads/photos/"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EntityListener\ConferenceEntityListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: 'prePersist', entity: 'App\Entity\Conference' }
            - { name: doctrine.orm.entity_listener, event: 'preUpdate', entity: 'App\Entity\Conference' }
